version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: investment_portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Server
  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: investment_portfolio
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      NODE_ENV: production
      CLIENT_URL: http://localhost:3000
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: ./uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - server_uploads:/app/uploads

  # Frontend Client
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  postgres_data:
  server_uploads: