# Configuración optimizada para Netlify - Sin errores 502
[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

# Variables de entorno para producción
[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "portfolio-manager-secret-key-2024-production"
  NODE_ENV = "production"
  CLIENT_URL = "https://admincarteras.netlify.app"

# Redirecciones para API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirección para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones optimizada
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers de seguridad y CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para API - SIN ERRORES 502
[[headers]]
  for = "/.netlify/functions/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "false"
    Cache-Control = "no-cache, no-store, must-revalidate"