[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "portfolio-manager-secret-key-2024-production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
