[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "portfolio-manager-secret-key-2024-production"
  NODE_ENV = "production"
  CLIENT_URL = "https://admincarteras.netlify.app"
  # Force Node.js 18 runtime for functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
