# Configuración específica para Netlify - Deploy Global
# Este archivo asegura que la aplicación funcione desde cualquier lugar

# Configuración de build
[build]
  command = "npm install && echo 'Build completado'"
  publish = "."
  functions = "netlify/functions"

# Variables de entorno para producción
[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "portfolio-manager-secret-key-2024-production"
  NODE_ENV = "production"
  CLIENT_URL = "https://admincarteras.netlify.app"

# Redirecciones para API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirección para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers de seguridad y CORS para acceso global
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers específicos para API - ACCESO GLOBAL
[[headers]]
  for = "/.netlify/functions/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "false"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers para archivos estáticos
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de plugins (opcional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"